# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/mybatis?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 修改页面不需要重启服务器
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  redis:
    host: localhost
    port: 6379
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package:  com.wpp.dao
